version: "3.4"

services:     

    #mamlakaapi api service
    mamlakaapi:
       image: shawn72/mamlakaapi:v0.1.0
       ports:
           - 7123:7123
       restart: always
       environment:
           - ASPNETCORE_ENVIRONMENT=Production
           - 'StaticStrings:DefaultActor=SYSTEM'
           - 'StaticStrings:DefaultGuid=00000000-0000-0000-0000-000000000000'
           - 'ConnectionStrings:DbConnectionString=Data Source={0};Database={1};Port={2};User Id={3};Password={4}; SSL Mode=None; AllowPublicKeyRetrieval=true;Convert Zero Datetime=true;Allow Zero DateTime=true;default command timeout=120' 
           - 'ConnectionStrings:Redis_Connection_String=redis://188.166.53.203:7070'
           - 'DatabaseSpecs:DataSource=replace-with-you-ip-address'
           - 'DatabaseSpecs:Database=mamlaka_api_db' 
           - 'DatabaseSpecs:Port=3309'
           - 'DatabaseSpecs:UserId=root'
           - 'DatabaseSpecs:Password=replace-with-your-password'
           - 'Server:backendServer=prod'
           - 'Security:Key=CaptainJ@ckSParrowCaptainJ@ck2Par'
           - 'Security:Issuer=ninjaxco.com'
           - 'Security:Audience=*.ninjaxco.com'
           - 'Security:SessionLifeTimeInMinutes=30'
           - 'PayPal:ClientId=Ac6u-uj4IYewZQbBjqFA1jhOhnN5axyDputUodLqoapwDWO8A7P_BI2gakImJL_K5NdWs2NjFaue1uR0'
           - 'PayPal:ClientSecret=ELDWfgBQWwNdiejhh3-NfcbaV1UgbHzpJWn0dMMHO3DwwGRZSPXW7tOjR5akcAQFVDiouUWfUHJqQAww'
           - 'PayPal:Mode=sandbox'
       networks:
           - asgard-midlands  
  
#define networks
networks:
  asgard-midlands:
      external: true
      driver: bridge
        
    
